In [3]:
# with open('./drive/MyDrive/ReadME.md', 'w') as f:
#     data = f.write('*반가워요.')
#     print('저장되었습니다.')

# 넘파이(numpy)

## 1차원과 속성들

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype: 배열 원소의 자료형

In [17]:
#pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry, type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[4])
print(narry[2:4])

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
4
[2 3]


In [20]:
narr1 = np.array([1, 2, 3, 4])
narr2 = np.array([1, 2, 'a', 'b'])
narr3 = np.array([1, 2, 3, 4],dtype = 'str')
print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [93]:
narr4 = np.zeros((2, 2), dtype = 'int64')
narr5 = np.ones((2, 2))
narr6 = np.full((3, 3), 3)
narr7 = np.full((3, 3), 'number')
narr8 = np.eye(3)
narr9 = np.linspace(0, 100, 5, endpoint = False, dtype = 'int64')
narr10 = np.linspace(0, 100, 20)
print(narr4, narr4.ndim, narr4.dtype, narr4.shape, narr4.size, type(narr4))
print(narr5, narr5.ndim, narr5.dtype, narr5.shape, narr5.size, type(narr5))
print(narr6, narr6.ndim, narr6.dtype, narr6.shape, narr6.size, type(narr6))
print(narr7, narr7.ndim, narr7.dtype, narr7.shape, narr7.size, type(narr7))
print(narr8, narr8.ndim, narr8.dtype, narr8.shape, narr8.size, type(narr8))
print(narr9, narr9.ndim, narr9.dtype, narr9.shape, narr9.size, type(narr9))
print(narr10, narr10.ndim, narr10.dtype, narr10.shape, narr10.size, type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ] 1 float64 (20,) 20 <class 'numpy.ndarray'>


## 2차원 배열

In [54]:
print(list(range(2, 10)))
print(np.arange(2, 10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr1 = np.array([[0, 0], [0, 0]])
print(arr1, arr1.ndim, type(arr1), arr1.dtype, arr1.shape, arr1.size)

[[0 0]
 [0 0]] 2 <class 'numpy.ndarray'> int64 (2, 2) 4


In [60]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8 ,9]).reshape(3, 3)
arr3 = np.arange(1, 10).reshape(3, 3)
arr4 = np.arange(1, 11).reshape(2, 5)
arr5 = np.arange(1, 11).reshape(5, 2)
arr6 = np.arange(1, 28).reshape(3, 3, 3)
print('차원', arr2.ndim, '/ 데이터타입', arr2.dtype, '/ 형태', arr2.shape, '/ 크기', arr2.size, type(arr2), arr2)
print('차원', arr3.ndim, '/ 데이터타입', arr3.dtype, '/ 형태', arr3.shape, '/ 크기', arr3.size, type(arr3), arr3)
print('차원', arr4.ndim, '/ 데이터타입', arr4.dtype, '/ 형태', arr4.shape, '/ 크기', arr4.size, type(arr4), arr4)
print('차원', arr5.ndim, '/ 데이터타입', arr5.dtype, '/ 형태', arr5.shape, '/ 크기', arr5.size, type(arr5), arr5)
print('차원', arr6.ndim, '/ 데이터타입', arr6.dtype, '/ 형태', arr6.shape, '/ 크기', arr6.size, type(arr6), arr6)

차원 2 / 데이터타입 int64 / 형태 (3, 3) / 크기 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원 2 / 데이터타입 int64 / 형태 (3, 3) / 크기 9 <class 'numpy.ndarray'> [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원 2 / 데이터타입 int64 / 형태 (2, 5) / 크기 10 <class 'numpy.ndarray'> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원 2 / 데이터타입 int64 / 형태 (5, 2) / 크기 10 <class 'numpy.ndarray'> [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원 3 / 데이터타입 int64 / 형태 (3, 3, 3) / 크기 27 <class 'numpy.ndarray'> [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [85]:
arr1 = np.arange(1, 22).reshape(3, 7)
arr2 = np.arange(1, 8).reshape(7, 1)
arr3 = np.arange(1, 11).reshape(5, 2)
arr4 = np.arange(1, 13).reshape(4, 3, 1)
print(arr1)
print('=' * 25)
print(arr2)
print('=' * 25)
print(arr3)
print('=' * 25)
print(arr4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [95]:
for i in range(3):
    print(arr1[i][3:8])

[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [100]:
arr1[arr1 > 12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [101]:
arr1 % 2 == 0

array([[False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False]])

In [105]:
# test
print(arr1[1][2:5])
print(arr1)
print(arr1[1:3, 2:4])
print(arr1[1:3, 4:6])
print(arr1 % 2 == 0)

[10 11 12]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[10 11]
 [17 18]]
[[12 13]
 [19 20]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [109]:
# np 배열 연산 // shape가 같을 경우 원소별 연산이 가능
np1 = np.array([6, 7, 8, 9, 10])
np2 = np.array([1, 2, 3, 4, 5])
print('덧셈 : ', np1 + np2)
print('뺄셈 : ', np1 - np2)
print('곱셈 : ', np1 * np2)
print('나눗셈 : ', np1 / np2)

덧셈 :  [ 7  9 11 13 15]
뺄셈 :  [5 5 5 5 5]
곱셈 :  [ 6 14 24 36 50]
나눗셈 :  [6.         3.5        2.66666667 2.25       2.        ]


In [110]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [112]:
br1 = np.arange(1, 10).reshape(3, 3)
br2 = np.array([11, 22, 33])
print(br1)
print('=====스칼라와 연산=====')
print(br1 + 3)
print(br1 + 2)
print('=====2D 와 1D 의 연산=====')
print(br2)
print(br1 + br2)
print(br1 * br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
=====스칼라와 연산=====
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
=====2D 와 1D 의 연산=====
[11 22 33]
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [118]:
# flatten 처리
ff = np.arange(1, 10).reshape(3, 3)
print(ff)
print(ff.reshape(1, 9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

## random unmber 발생

- np.random.randint(): 균일 분포의 정수 난수\n",
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성\n",
- np.random.randn(): 표준 정규 분포 난수 생성\n",
- np.random.normal(): 정규 분포 난수 생성"

In [62]:
# randomint
import numpy as np
x = np.random.randint(0, 255, size = (3, 3, 3))
x

array([[[  1, 111, 220],
        [182, 231, 156],
        [157, 150,  24]],

       [[226,  17, 108],
        [ 33,  76, 137],
        [151, 140, 116]],

       [[186,  42, 109],
        [ 70, 158, 211],
        [ 93,   2, 201]]], dtype=int32)

In [65]:
print('평균값 :', np.mean(x), '표준편차 :' , np.std(x), '최소값 :', np.min(x), '최대값 :', np.max(x))

평균값 : 122.51851851851852 표준편차 : 69.43601924200136 최소값 : 1 최대값 : 231


In [66]:
print(len(x.flatten()))

27


In [68]:
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5,34,3,3,23,0,1,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
22


# 판다스(pandas)

- 시리즈(series)
- 데이터프레임(dataframe)

In [2]:
import numpy as np
import pandas as pd

In [14]:
data1 = np.arange(1, 11)
print(data1)
data2 = pd.Series(data1)
print(data2, type(data2), data2.index, data2.values, data2.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=10, step=1) [ 1  2  3  4  5  6  7  8  9 10] int64


In [1]:
# !pip install pandas

In [10]:
# 판다스 시리즈의 데이터타입
data3 = pd.Series([1, 2, 3.14, 4, 5, 6, 7])
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
5    6.00
6    7.00
dtype: float64


In [13]:
# 판다스 시리즈의 인덱스 설정
data3 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [25]:
# 판다스 시리즈 딕셔너리데이터
population_dict = {
    'korea' : 5182,
    'japan' : 12622,
    'china' : 141178,
    'usa' : 38976
}
# population_dict.keys()
# population_dict.values()
# population_dict.items()
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
print(country.loc['usa'])
print(country.iloc[3])

korea      5182
japan     12622
china    141178
usa       38976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  38976]
1 (4,) 4
38976
38976


In [26]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], index = ['a', 'b', 'c'], columns = ['A', 'B', 'C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [49]:
# 테스트
import numpy as np
import pandas as pd

# 두 개의 시리즈 데이터
print("인구수 시리즈 데이터 :")
population_dict = {
    'korea' : 5182,
    'japan' : 12622,
    'china' : 141178,
    'usa' : 38976
}
population = pd.Series(population_dict)
print(population)

print("GDP 시리즈 데이터 :")
GDP_dict = {
    'korea' : 169320000,
    'japan' : 516700000,
    'china' : 140925000,
    'usa' : 2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('=' * 25)
print('데이터 프레임 생성')
country = pd.DataFrame({'population' : population, 'GDP' : GDP})
country.index.name = 'Country' # 인덱스 이름을 지정
country.columns.name = 'Info' # 컬럼 이름 지정
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)

인구수 시리즈 데이터 :
korea      5182
japan     12622
china    141178
usa       38976
dtype: int64
GDP 시리즈 데이터 :
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'GDP'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     38976 2041280000]] (4, 2) 8 2


In [50]:
# 데이터 프레임의 요소 접근 방법 loc, iloc
country.loc['korea'], country.loc['usa']
country.iloc[2], country.iloc[1]

(Info
 population       141178
 GDP           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 GDP           516700000
 Name: japan, dtype: int64)

In [51]:
country.loc['korea' : 'japan', :'population']

Info     population
Country            
korea          5182
japan         12622

In [52]:
country.iloc[0:2, :1]

Info     population
Country            
korea          5182
japan         12622

In [53]:
#country.loc['japan' : 'usa', 'GDP':]
country.iloc[1:4, 1:]

Info            GDP
Country            
japan     516700000
china     140925000
usa      2041280000

In [54]:
country.loc['japan' : 'china', :'GDP']
#country.iloc[1:3, :2]

Info     population        GDP
Country                       
japan         12622  516700000
china        141178  140925000

In [8]:
# 컬럼 추가
#country['test'] = [11, 22, 33, 44]
#country = country.drop('test', axis = 1)
gdpper = country['GDP'] / country['population']
country['gdp_per'] = gdpper
country

Info     population         GDP       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           38976  2041280000  52372.742200

In [21]:
# 행 추가 방법1
country.loc['india'] = [142222, 150505000, 'NaN']
country.loc['india', 'gdp_per'] = country.loc['india', 'GDP'] / country.loc['india', 'population']
country

Info     population           GDP       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         38976.0  2.041280e+09    52372.7422
india      142222.0  1.505050e+08   1058.239935

In [22]:
# 행 추가 방법2
africa = pd.Series(data = [123456, 7777777], index = ['population', 'GDP'])
country.loc['africa'] = africa
country.loc['africa', 'gdp_per'] = country.loc['africa', 'GDP'] / country.loc['africa', 'population']
country

Info     population           GDP       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         38976.0  2.041280e+09    52372.7422
india      142222.0  1.505050e+08   1058.239935
africa     123456.0  7.777777e+06     63.000397

In [23]:
#결측값(NaN) 확인
country.isnull().sum()

Info
population    0
GDP           0
gdp_per       0
dtype: int64

In [24]:
# 열 제거 drop(이름, axis = )
country = country.drop('africa', axis= 0) # inplace = True
country

Info     population           GDP       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         38976.0  2.041280e+09    52372.7422
india      142222.0  1.505050e+08   1058.239935

In [25]:
# 테스트 1 조건
country['population'] > 140000

Country
korea    False
japan    False
china     True
usa      False
india     True
Name: population, dtype: bool

In [36]:
# 테스트2 조건, 슬라이싱 (loc, iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:, :'population']

Info     population
Country            
japan       12622.0
usa         38976.0

In [75]:
# 키값쌍으로 리스트에 저장하는 방법
# data = [
#    {'이름' : '홍길동', '국어' : 80, '수학' : 70, '영어' : 80}
#    {'이름' : '박철수', '국어' : 60, '수학' : 70, '영어' : 80}
#    {'이름' : '김영희', '국어' : 70, '수학' : 90, '영어' : 80}
#]

# 리스트에 튜플로 저장하는 방법
# data = [
#     ('홍길동', 80, 70, 80),
#     ('박철수', 60, 70, 80),
#     ('김영희', 70, 90, 80)
# ]
# df = pd.DataFrame(data, columns = ['이름', '국어', '수학', '영어'])
# df

ko_dict = {
    '홍길동' : 80,
    '박철수' : 60,
    '김영희' : 70
}
math_dict = {
    '홍길동' : 70,
    '박철수' : 70,
    '김영희' : 90
}
en_dict = {
    '홍길동' : 80,
    '박철수' : 80,
    '김영희' : 80
}
ko = pd.Series(ko_dict)
math = pd.Series(math_dict)
en = pd.Series(en_dict)
student = pd.DataFrame({'국어' : ko, '수학' : math, '영어' : en})
student.columns.name = '이름'
student

이름   국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [65]:
student.iloc[1:2, 1:3]

이름   수학  영어
박철수  70  80

In [78]:
student[student['국어'] >= 70]

이름   국어  수학  영어
홍길동  80  70  80
김영희  70  90  80

In [81]:
student['평균'] = (student['국어'] + student['수학'] + student['영어']) / 3
student.round()

이름   국어  수학  영어    평균
홍길동  80  70  80  77.0
박철수  60  70  80  70.0
김영희  70  90  80  80.0

In [72]:
java = pd.Series(data = [55, 95, 70], index = ['국어', '수학', '영어'])
student.loc['최자바'] = java
student.loc['최자바', '평균'] = (student.loc['최자바', '국어'] + student.loc['최자바', '수학'] + student.loc['최자바', '영어']) / 3
student

이름     국어    수학    영어         평균
홍길동  80.0  70.0  80.0  76.666667
박철수  60.0  70.0  80.0  70.000000
김영희  70.0  90.0  80.0  80.000000
최자바  55.0  95.0  70.0  73.333333

In [ ]:
# 리스트에 튜플로 저장하는 방법
# data0 = [
#     ('홍길동', 80, 70, 80),
#     ('박철수', 60, 70, 80),
#     ('김영희', 70, 90, 80)
# ]
# data = np.array(data0)
# data = np.array([['홍길동', 80, 70, 80], ['박철수', 60, 70, 80], ['김영희', 70, 90, 80]])
# data